import { cn } from "@/lib/utils";

/**
 * Tiny "AI" badge for content generated by Claude. Light enough to not
 * distract on camera but present enough to communicate provenance.
 *
 * Use `inline` for placement next to a heading; default is an absolute
 * placement in the top-right of a `relative` container.
 */
export default function AiTag({
  inline = false,
  className,
  label = "AI",
}: {
  inline?: boolean;
  className?: string;
  label?: string;
}) {
  return (
    <span
      className={cn(
        "text-[9px] uppercase tracking-[0.18em] font-mono text-text-tertiary leading-none select-none",
        inline ? "inline-flex items-center" : "absolute top-2 right-2",
        className,
      )}
      aria-label="AI-generated"
    >
      {label}
    </span>
  );
}
